apiVersion: v1
kind: Service
metadata:
  name: service-loki
  namespace: macf
spec:
  selector:
    app: deploy-loki
  type: LoadBalancer
  ports:
    - name: service-loki
      protocol: TCP
      port: 3100
      targetPort: 3100
