apiVersion: v1
kind: Service
metadata:
  name: service-elastic
  namespace: macf
spec:
  selector:
    app: service-elastic
  type: LoadBalancer
  ports:
    - name: service-elastic
      protocol: TCP
      port: 9200
      targetPort: 9200
